doctrine_migrations:
    dir_name: "%kernel.project_dir%/src/Migrations"
    namespace: DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: "BY_YEAR_AND_MONTH" # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false