doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.3'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%database_url%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
