fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\User\RegistrationType
            name: app_user_registration
    service:
        mailer: app.user.mailer.rest
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_username%"
