services:
    _defaults:
        public: true
        autoconfigure: true
        autowire: true

    test.user.service: '@App\Services\Entity\UserService'


    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
